### ISSUE TITLE
Please release a more recent version of this package

### ISSUE THREAD

**Issue by chrischu** [microsoft/vs-validation#169]
I'm currently trying to update dependencies in my solution to versions corresponding to the new VS version, but I'm running into a problem: the NuGet Package **Microsoft.VisualStudio.LanguageServices** in version **4.5.0-2.final** references **Mcirosoft.VisualStudio.Validation** in version **>= 17.0.71** but the only available non-prerelease version of it on NuGet is **17.0.65**.

Could you please release a more recent non-prerelease version of this package on NuGet? Thanks in advance!

**Comment by AArnott** [comment]
17.0.71 pushed to nuget.org.

Thank you for reaching out.
