### ISSUE TITLE
Assumes.NotNull support Nullable<T> struct

### ISSUE THREAD

**Issue by iron9light** [microsoft/vs-validation#43]
Now, Assumes.NotNull only supports reference type as a parameter.

**Comment by iron9light** [comment]
Should I use `Assumes.Present<T>` for this case?

**Comment by AArnott** [comment]
No, `Present<T>` is meant for service non-null checks.
You can use `Assumes.True(nullableStruct.HasValue);` instead.

**Comment by AArnott** [comment]
Actually looking at the API we offer, this was addressed by #45
