### ISSUE TITLE
Package project URL is wrong

### ISSUE THREAD

**Issue by scottdorman** [microsoft/vs-validation#63]
https://github.com/microsoft/vs-validation/blob/c209212b710bc3e0038077ca92d9e0a30253dc02/src/Directory.Build.props#L5

**Comment by scottdorman** [comment]
Just a reminder that this still needs to be merged into master as well.

**Comment by AArnott** [comment]
That's fine. I don't merge servicing branches to master too frequently. Right now v16.8 is stabilizing. When we release it, I'll do a merge to master.
