### ISSUE TITLE
Overload Requires.NotNullOrEmpty to avoid enumerator allocation

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/vs-validation#77]
I'm looking at a CPS trace where `Requires.NotNullOrEmpty` is allocating a fair number of enumerators. The type is statically known to implement `IReadOnlyCollection<T>`, so an overload that accepted that type could make the cheaper call to `Count`.

Unfortunately it's unclear which interfaces to support. With overloads for both `ICollection<T>` and `IReadOnlyCollection<T>`, calling `Requires.NotNullOrEmpty(new List<int>(), "")` would not compile due to ambiguity, which isn't a great experience. Is there a clean way to get this benefit for common types without runtime type checks?

I can rewrite the code to avoid the allocations, but it'd be better if this applied across the board for free by simply compiling against a newer version of the library.

**Comment by AArnott** [comment]
Good find! I suppose from your description that the allocation is coming from here:

https://github.com/microsoft/vs-validation/blob/367128db4e17d6165880e38629cba51c91967d86/src/Microsoft.VisualStudio.Validation/Requires.cs#L222-L226

We could avoid the allocation by adding this above that code:

```cs
if (values is IReadOnlyCollection<T> collection)
{
  if (collection.Count == 0)
  {
    throw new ArgumentException(Format(Strings.Argument_EmptyArray, parameterName), parameterName);
  }
}
else
{
   // the enumerator code.
}
```

**Comment by drewnoakes** [comment]
Yes that's the one.

I'd hoped we could avoid a runtime type check for instances where the calling code has a type with a `Count` property, but I can't see a way to avoid the ambiguous overload errors it might introduce.

For runtime types, should this also include `ICollection<T>` and `ICollection`?

**Comment by AArnott** [comment]
I imagine the optimization to avoid the enumeration will be far better than the minimal cost of a runtime type check.
As for the additional two types, we could check those too.

Wanna send a PR?

**Comment by drewnoakes** [comment]
Sure.

Turns out we can overload for `ICollection<T>` as that is a subtype of `IEnumerable<T>` so will always be favoured, hence no ambiguity.

I'll add an overload, and add a runtime checks for `IReadOnlyCollection<T>` to the `IEnumerable<T>` version.

We can also give the same treatment to `Assumes.NotNullOrEmpty`.
